<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto

namespace App\Grpc\GPBMetadata;

class Greeter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD2\x01\x0A\x0Dgreeter.proto\x12\x10app.grpc.greeter\"\x1C\x0A\x0CHelloRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"\x1D\x0A\x0AHelloReply\x12\x0F\x0A\x07message\x18\x01 \x01(\x092U\x0A\x07Greeter\x12J\x0A\x08SayHello\x12\x1E.app.grpc.greeter.HelloRequest\x1A\x1C.app.grpc.greeter.HelloReply\"\x00B\x13\xCA\x02\x10App\\Grpc\\Greeterb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

